# Generated by Django 2.1.7 on 2019-07-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeeAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('agent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BeesPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.IntegerField()),
                ('iteration_count', models.IntegerField()),
                ('funcName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateAnts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateObcts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtacleX', models.FloatField()),
                ('obtacleY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FireflyAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('agent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FireflyPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_worms', models.IntegerField()),
                ('nturns', models.IntegerField()),
                ('influence_factor', models.IntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('max_jitter', models.FloatField()),
                ('function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FishAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('agent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FishesPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_size', models.IntegerField()),
                ('iteration_count', models.IntegerField()),
                ('weight_max', models.FloatField()),
                ('speed', models.FloatField()),
                ('min_x', models.FloatField()),
                ('max_x', models.FloatField()),
                ('min_y', models.FloatField()),
                ('max_y', models.FloatField()),
                ('error', models.FloatField()),
                ('function', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fishagent',
            name='population_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FishesPopulation'),
        ),
        migrations.AddField(
            model_name='fireflyagent',
            name='population_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FireflyPopulation'),
        ),
        migrations.AddField(
            model_name='beeagent',
            name='population_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BeesPopulation'),
        ),
    ]
