# Generated by Django 2.1.7 on 2019-07-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinateants',
            name='z',
        ),
    ]
